[project]
authors = ["Diesel AMM"]
entry = "main.sw"
license = "Apache-2.0"
name = "diesel_amm_proxy"

[dependencies]
interfaces = { path = "../../libraries/interfaces" }
math = { path = "../../libraries/math" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.2" }

utils = { path = "../../libraries/utils" }
